services:
  usuarios-service:
    build:
      context: ./services/usuarios
      dockerfile: Dockerfile
    container_name: usuarios_microservice
    ports:
      - "8001:8001"
    volumes:
      - ./services/usuarios/app:/app/app
    environment:
      - ENV=development

  produtos-service:
    build:
      context: ./services/produtos
      dockerfile: Dockerfile
    container_name: produtos_microservice
    ports:
      - "8002:8002"
    volumes:
      - ./services/produtos/app:/app/app
    environment:
      - ENV=development

  pedidos-service:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile
    container_name: pedidos_microservice
    ports:
      - "8003:8003"
    volumes:
      - ./services/pedidos/app:/app/app
    environment:
      - ENV=development
