services:
  usuarios-service:
    build:
      context: ./services/usuarios
      dockerfile: Dockerfile
    container_name: usuarios_microservice
    ports:
      - "8001:8001"
    volumes:
      - ./services/usuarios/app:/app/app
    environment:
      - ENV=development

  produtos-service:
    build:
      context: ./services/produtos
      dockerfile: Dockerfile
    container_name: produtos_microservice
    ports:
      - "8002:8002"
    volumes:
      - ./services/produtos/app:/app/app
    environment:
      - ENV=development

  pedidos-service:
    build:
      context: ./services/pedidos
      dockerfile: Dockerfile
    container_name: pedidos_microservice
    ports:
      - "8003:8003"
    volumes:
      - ./services/pedidos/app:/app/app
    environment:
      - ENV=development

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: graphql_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/app:/app/app
    environment:
      - ENV=development

  locust-tests:
    image: locustio/locust
    container_name: locust_benchmark
    ports:
      - "8089:8089"
    volumes:
      - ./tests:/mnt/locust
    depends_on:
      - gateway-service
    command: -f /mnt/locust/locustfile.py
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_tcc
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
